// Generated by CoffeeScript 1.9.1
(function() {
  var CatchAllMessage, EnterMessage, Message, TextMessage, User, chai, expect, ref, sinon;

  chai = require('chai');

  sinon = require('sinon');

  chai.use(require('sinon-chai'));

  expect = chai.expect;

  User = require('../src/user.js');

  ref = require('../src/message'), CatchAllMessage = ref.CatchAllMessage, EnterMessage = ref.EnterMessage, Message = ref.Message, TextMessage = ref.TextMessage;

  describe('Message', function() {
    beforeEach(function() {
      return this.user = new User({
        id: 1,
        name: 'hubottester',
        room: '#mocha'
      });
    });
    return describe('Unit Tests', function() {
      describe('#finish', function() {
        return it('marks the message as done', function() {
          var testMessage;
          testMessage = new Message(this.user);
          expect(testMessage.done).to.not.be.ok;
          testMessage.finish();
          return expect(testMessage.done).to.be.ok;
        });
      });
      return describe('TextMessage', function() {
        return describe('#match', function() {
          return it('should perform standard regex matching', function() {
            var testMessage;
            testMessage = new TextMessage(this.user, 'message123');
            expect(testMessage.match(/^message123$/)).to.be.ok;
            return expect(testMessage.match(/^does-not-match$/)).to.not.be.ok;
          });
        });
      });
    });
  });

}).call(this);
