// Generated by CoffeeScript 1.9.1
(function() {
  var Adapter, Brain, CatchAllMessage, EnterMessage, LeaveMessage, Listener, Message, Response, Robot, TextListener, TextMessage, TopicMessage, User, ref, ref1;

  User = require('./src/user');

  Brain = require('./src/brain');

  Robot = require('./src/robot');

  Adapter = require('./src/adapter');

  Response = require('./src/response');

  ref = require('./src/listener'), Listener = ref.Listener, TextListener = ref.TextListener;

  ref1 = require('./src/message'), Message = ref1.Message, TextMessage = ref1.TextMessage, EnterMessage = ref1.EnterMessage, LeaveMessage = ref1.LeaveMessage, TopicMessage = ref1.TopicMessage, CatchAllMessage = ref1.CatchAllMessage;

  module.exports = {
    User: User,
    Brain: Brain,
    Robot: Robot,
    Adapter: Adapter,
    Response: Response,
    Listener: Listener,
    TextListener: TextListener,
    Message: Message,
    TextMessage: TextMessage,
    EnterMessage: EnterMessage,
    LeaveMessage: LeaveMessage,
    TopicMessage: TopicMessage,
    CatchAllMessage: CatchAllMessage
  };

  module.exports.loadBot = function(adapterPath, adapterName, enableHttpd, botName) {
    return new Robot(adapterPath, adapterName, enableHttpd, botName);
  };

}).call(this);
