// Generated by CoffeeScript 1.9.1
(function() {
  var Brain, CatchAllMessage, EnterMessage, EventEmitter, Fs, HUBOT_DEFAULT_ADAPTERS, HUBOT_DOCUMENTATION_SECTIONS, HttpClient, LeaveMessage, Listener, Log, Path, Response, Robot, TextListener, TopicMessage, User, ref, ref1,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    slice = [].slice;

  require('babel/register');

  Fs = require('fs');

  Log = require('log');

  Path = require('path');

  HttpClient = require('scoped-http-client');

  EventEmitter = require('events').EventEmitter;

  User = require('./user');

  Brain = require('./brain');

  Response = require('./response');

  ref = require('./listener'), Listener = ref.Listener, TextListener = ref.TextListener;

  ref1 = require('./message'), EnterMessage = ref1.EnterMessage, LeaveMessage = ref1.LeaveMessage, TopicMessage = ref1.TopicMessage, CatchAllMessage = ref1.CatchAllMessage;

  HUBOT_DEFAULT_ADAPTERS = ['campfire', 'shell'];

  HUBOT_DOCUMENTATION_SECTIONS = ['description', 'dependencies', 'configuration', 'commands', 'notes', 'author', 'authors', 'examples', 'tags', 'urls'];

  Robot = (function() {
    function Robot(adapterPath, adapter, httpd, name) {
      if (name == null) {
        name = 'Hubot';
      }
      this.name = name;
      this.events = new EventEmitter;
      this.brain = new Brain(this);
      this.alias = false;
      this.adapter = null;
      this.Response = Response;
      this.commands = [];
      this.listeners = [];
      this.logger = new Log(process.env.HUBOT_LOG_LEVEL || 'info');
      this.pingIntervalId = null;
      this.parseVersion();
      if (httpd) {
        this.setupExpress();
      } else {
        this.setupNullRouter();
      }
      this.loadAdapter(adapterPath, adapter);
      this.adapterName = adapter;
      this.errorHandlers = [];
      this.on('error', (function(_this) {
        return function(err, msg) {
          return _this.invokeErrorHandlers(err, msg);
        };
      })(this));
      this.onUncaughtException = (function(_this) {
        return function(err) {
          return _this.emit('error', err);
        };
      })(this);
      process.on('uncaughtException', this.onUncaughtException);
    }

    Robot.prototype.hear = function(regex, callback) {
      return this.listeners.push(new TextListener(this, regex, callback));
    };

    Robot.prototype.respond = function(regex, callback) {
      var alias, modifiers, name, newRegex, pattern, re;
      re = regex.toString().split('/');
      re.shift();
      modifiers = re.pop();
      if (re[0] && re[0][0] === '^') {
        this.logger.warning("Anchors don't work well with respond, perhaps you want to use 'hear'");
        this.logger.warning("The regex in question was " + (regex.toString()));
      }
      pattern = re.join('/');
      name = this.name.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
      if (this.alias) {
        alias = this.alias.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
        newRegex = new RegExp("^\\s*[@]?(?:" + alias + "[:,]?|" + name + "[:,]?)\\s*(?:" + pattern + ")", modifiers);
      } else {
        newRegex = new RegExp("^\\s*[@]?" + name + "[:,]?\\s*(?:" + pattern + ")", modifiers);
      }
      return this.listeners.push(new TextListener(this, newRegex, callback));
    };

    Robot.prototype.enter = function(callback) {
      return this.listeners.push(new Listener(this, (function(msg) {
        return msg instanceof EnterMessage;
      }), callback));
    };

    Robot.prototype.leave = function(callback) {
      return this.listeners.push(new Listener(this, (function(msg) {
        return msg instanceof LeaveMessage;
      }), callback));
    };

    Robot.prototype.topic = function(callback) {
      return this.listeners.push(new Listener(this, (function(msg) {
        return msg instanceof TopicMessage;
      }), callback));
    };

    Robot.prototype.error = function(callback) {
      return this.errorHandlers.push(callback);
    };

    Robot.prototype.invokeErrorHandlers = function(err, msg) {
      var errErr, errorHandler, i, len, ref2, results1;
      this.logger.error(err.stack);
      ref2 = this.errorHandlers;
      results1 = [];
      for (i = 0, len = ref2.length; i < len; i++) {
        errorHandler = ref2[i];
        try {
          results1.push(errorHandler(err, msg));
        } catch (_error) {
          errErr = _error;
          results1.push(this.logger.error("while invoking error handler: " + errErr + "\n" + errErr.stack));
        }
      }
      return results1;
    };

    Robot.prototype.catchAll = function(callback) {
      return this.listeners.push(new Listener(this, (function(msg) {
        return msg instanceof CatchAllMessage;
      }), (function(msg) {
        msg.message = msg.message.message;
        return callback(msg);
      })));
    };

    Robot.prototype.receive = function(message) {
      var error, i, len, listener, ref2, results;
      results = [];
      ref2 = this.listeners;
      for (i = 0, len = ref2.length; i < len; i++) {
        listener = ref2[i];
        try {
          results.push(listener.call(message));
          if (message.done) {
            break;
          }
        } catch (_error) {
          error = _error;
          this.emit('error', error, new this.Response(this, message, []));
          false;
        }
      }
      if (!(message instanceof CatchAllMessage) && results.indexOf(true) === -1) {
        return this.receive(new CatchAllMessage(message));
      }
    };

    Robot.prototype.loadFile = function(path, file) {
      var error, ext, full, script;
      ext = Path.extname(file);
      full = Path.join(path, Path.basename(file, ext));
      if (require.extensions[ext]) {
        try {
          script = require(full);
          if (typeof script === 'function') {
            script(this);
            return this.parseHelp(Path.join(path, file));
          } else {
            return this.logger.warning("Expected " + full + " to assign a function to module.exports, got " + (typeof script));
          }
        } catch (_error) {
          error = _error;
          this.logger.error("Unable to load " + full + ": " + error.stack);
          return process.exit(1);
        }
      }
    };

    Robot.prototype.load = function(path) {
      var file, i, len, ref2, results1;
      this.logger.debug("Loading scripts from " + path);
      if (Fs.existsSync(path)) {
        ref2 = Fs.readdirSync(path).sort();
        results1 = [];
        for (i = 0, len = ref2.length; i < len; i++) {
          file = ref2[i];
          results1.push(this.loadFile(path, file));
        }
        return results1;
      }
    };

    Robot.prototype.loadHubotScripts = function(path, scripts) {
      var i, len, results1, script;
      this.logger.debug("Loading hubot-scripts from " + path);
      results1 = [];
      for (i = 0, len = scripts.length; i < len; i++) {
        script = scripts[i];
        results1.push(this.loadFile(path, script));
      }
      return results1;
    };

    Robot.prototype.loadExternalScripts = function(packages) {
      var err, i, len, pkg, results1, results2, scripts;
      this.logger.debug("Loading external-scripts from npm packages");
      try {
        if (packages instanceof Array) {
          results1 = [];
          for (i = 0, len = packages.length; i < len; i++) {
            pkg = packages[i];
            results1.push(require(pkg)(this));
          }
          return results1;
        } else {
          results2 = [];
          for (pkg in packages) {
            scripts = packages[pkg];
            results2.push(require(pkg)(this, scripts));
          }
          return results2;
        }
      } catch (_error) {
        err = _error;
        this.logger.error("Error loading scripts from npm package - " + err.stack);
        return process.exit(1);
      }
    };

    Robot.prototype.setupExpress = function() {
      var address, app, err, express, herokuUrl, pass, port, stat, user;
      user = process.env.EXPRESS_USER;
      pass = process.env.EXPRESS_PASSWORD;
      stat = process.env.EXPRESS_STATIC;
      port = process.env.EXPRESS_PORT || process.env.PORT || 8080;
      address = process.env.EXPRESS_BIND_ADDRESS || process.env.BIND_ADDRESS || '0.0.0.0';
      express = require('express');
      app = express();
      app.use((function(_this) {
        return function(req, res, next) {
          res.setHeader("X-Powered-By", "hubot/" + _this.name);
          return next();
        };
      })(this));
      if (user && pass) {
        app.use(express.basicAuth(user, pass));
      }
      app.use(express.query());
      app.use(express.bodyParser());
      if (stat) {
        app.use(express["static"](stat));
      }
      try {
        this.server = app.listen(port, address);
        this.router = app;
      } catch (_error) {
        err = _error;
        this.logger.error("Error trying to start HTTP server: " + err + "\n" + err.stack);
        process.exit(1);
      }
      herokuUrl = process.env.HEROKU_URL;
      if (herokuUrl) {
        if (!/\/$/.test(herokuUrl)) {
          herokuUrl += '/';
        }
        return this.pingIntervalId = setInterval((function(_this) {
          return function() {
            return HttpClient.create(herokuUrl + "hubot/ping").post()(function(err, res, body) {
              return _this.logger.info('keep alive ping!');
            });
          };
        })(this), 5 * 60 * 1000);
      }
    };

    Robot.prototype.setupNullRouter = function() {
      var msg;
      msg = "A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.";
      return this.router = {
        get: (function(_this) {
          return function() {
            return _this.logger.warning(msg);
          };
        })(this),
        post: (function(_this) {
          return function() {
            return _this.logger.warning(msg);
          };
        })(this),
        put: (function(_this) {
          return function() {
            return _this.logger.warning(msg);
          };
        })(this),
        "delete": (function(_this) {
          return function() {
            return _this.logger.warning(msg);
          };
        })(this)
      };
    };

    Robot.prototype.loadAdapter = function(path, adapter) {
      var err;
      this.logger.debug("Loading adapter " + adapter);
      try {
        path = indexOf.call(HUBOT_DEFAULT_ADAPTERS, adapter) >= 0 ? path + "/" + adapter : "hubot-" + adapter;
        return this.adapter = require(path).use(this);
      } catch (_error) {
        err = _error;
        this.logger.error("Cannot load adapter " + adapter + " - " + err);
        return process.exit(1);
      }
    };

    Robot.prototype.helpCommands = function() {
      return this.commands.sort();
    };

    Robot.prototype.parseHelp = function(path) {
      var body, cleanedLine, currentSection, i, j, len, len1, line, nextSection, ref2, ref3, results1, scriptDocumentation, scriptName;
      this.logger.debug("Parsing help for " + path);
      scriptName = Path.basename(path).replace(/\.(coffee|js)$/, '');
      scriptDocumentation = {};
      body = Fs.readFileSync(path, 'utf-8');
      currentSection = null;
      ref2 = body.split("\n");
      for (i = 0, len = ref2.length; i < len; i++) {
        line = ref2[i];
        if (!(line[0] === '#' || line.substr(0, 2) === '//')) {
          break;
        }
        cleanedLine = line.replace(/^(#|\/\/)\s?/, "").trim();
        if (cleanedLine.length === 0) {
          continue;
        }
        if (cleanedLine.toLowerCase() === 'none') {
          continue;
        }
        nextSection = cleanedLine.toLowerCase().replace(':', '');
        if (indexOf.call(HUBOT_DOCUMENTATION_SECTIONS, nextSection) >= 0) {
          currentSection = nextSection;
          scriptDocumentation[currentSection] = [];
        } else {
          if (currentSection) {
            scriptDocumentation[currentSection].push(cleanedLine.trim());
            if (currentSection === 'commands') {
              this.commands.push(cleanedLine.trim());
            }
          }
        }
      }
      if (currentSection === null) {
        this.logger.info(path + " is using deprecated documentation syntax");
        scriptDocumentation.commands = [];
        ref3 = body.split("\n");
        results1 = [];
        for (j = 0, len1 = ref3.length; j < len1; j++) {
          line = ref3[j];
          if (!(line[0] === '#' || line.substr(0, 2) === '//')) {
            break;
          }
          if (!line.match('-')) {
            continue;
          }
          cleanedLine = line.slice(2, +line.length + 1 || 9e9).replace(/^hubot/i, this.name).trim();
          scriptDocumentation.commands.push(cleanedLine);
          results1.push(this.commands.push(cleanedLine));
        }
        return results1;
      }
    };

    Robot.prototype.send = function() {
      var ref2, strings, user;
      user = arguments[0], strings = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return (ref2 = this.adapter).send.apply(ref2, [user].concat(slice.call(strings)));
    };

    Robot.prototype.reply = function() {
      var ref2, strings, user;
      user = arguments[0], strings = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return (ref2 = this.adapter).reply.apply(ref2, [user].concat(slice.call(strings)));
    };

    Robot.prototype.messageRoom = function() {
      var ref2, room, strings, user;
      room = arguments[0], strings = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      user = {
        room: room
      };
      return (ref2 = this.adapter).send.apply(ref2, [user].concat(slice.call(strings)));
    };

    Robot.prototype.on = function() {
      var args, event, ref2;
      event = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return (ref2 = this.events).on.apply(ref2, [event].concat(slice.call(args)));
    };

    Robot.prototype.emit = function() {
      var args, event, ref2;
      event = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return (ref2 = this.events).emit.apply(ref2, [event].concat(slice.call(args)));
    };

    Robot.prototype.run = function() {
      this.emit("running");
      return this.adapter.run();
    };

    Robot.prototype.shutdown = function() {
      if (this.pingIntervalId != null) {
        clearInterval(this.pingIntervalId);
      }
      process.removeListener('uncaughtException', this.onUncaughtException);
      this.adapter.close();
      return this.brain.close();
    };

    Robot.prototype.parseVersion = function() {
      var pkg;
      pkg = require(Path.join(__dirname, '..', 'package.json'));
      return this.version = pkg.version;
    };

    Robot.prototype.http = function(url, options) {
      return HttpClient.create(url, options).header('User-Agent', "Hubot/" + this.version);
    };

    return Robot;

  })();

  module.exports = Robot;

}).call(this);
